export type StringIncludes<
	T extends string,
	U extends string
> = T extends `${any}${U}${any}` ? true : false;
const str = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam imperdiet, mi eu semper auctor, augue ipsum pellentesque ligula, aliquet laoreet nunc velit id turpis. Vestibulum porttitor placerat nisl. Pellentesque auctor risus in dolor blandit pulvinar. Sed non lobortis ipsum. Curabitur vitae orci nec nisi hendrerit scelerisque sed ac arcu. Phasellus in imperdiet elit. Fusce ex ante, tempor quis pulvinar quis, sodales in quam. Aliquam lacinia nec risus nec mollis. Sed nec molestie lacus. Pellentesque malesuada turpis vel risus luctus consectetur. Quisque risus est, placerat eu tellus in, interdum sodales tortor. Cras cursus dolor in dolor sollicitudin, eget elementum libero cursus.

Integer ultricies risus vitae tellus congue aliquam. Donec lobortis malesuada tortor sit amet semper. Praesent aliquam pharetra sem, sed gravida risus porta in. Mauris sed justo vel ligula tempor tincidunt. Curabitur facilisis tellus vel odio pretium, fermentum imperdiet magna pellentesque. Quisque venenatis, risus in mollis consectetur, tellus erat tristique tortor, a malesuada ante tortor ac diam. Nunc congue nisi metus, ut ultricies eros placerat sit amet. Donec quis venenatis sem, ac ullamcorper erat. Aenean libero odio, sagittis nec tortor quis, bibendum laoreet metus. Maecenas ac enim eget diam consectetur iaculis vel id sem. Nunc est ante, interdum eget tristique vel, sollicitudin vitae quam. Praesent nec nisl ut nisl placerat sodales vel vulputate tellus. Vivamus eget accumsan nibh.

Curabitur tempor dolor eu risus consectetur, sit amet accumsan risus euismod. In a varius orci, vitae ornare urna. Nulla porttitor felis et ligula fringilla egestas. Nunc eget ipsum eu nulla suscipit rutrum eget sed dui. Sed tincidunt, nibh ut scelerisque mollis, felis turpis volutpat libero, a ultricies elit ex non massa. In rhoncus facilisis ullamcorper. Morbi lectus leo, malesuada et mauris et, dignissim ultricies ligula. Aliquam felis tellus, finibus ut malesuada vitae, scelerisque eu leo. Nam a felis faucibus, sodales neque ac, aliquet massa. Duis ex leo, tincidunt ac urna sit amet, laoreet hendrerit libero. Cras mattis velit vitae vulputate feugiat.

Morbi vitae sollicitudin mi. Duis varius condimentum nunc sed vulputate. Ut lacinia tempus feugiat. Cras sed bibendum ante. Fusce imperdiet eros in lorem ultrices, sed mollis magna mollis. Aliquam tempus orci lorem, eget pretium mauris bibendum at. Maecenas ligula nisi, volutpat et sem at, congue venenatis nisi. Aenean eget lacus quis felis dignissim euismod sit amet eu tellus. Fusce luctus iaculis convallis. Phasellus ultrices lacus eget tellus feugiat, sit amet dignissim eros vestibulum. Aliquam eget turpis urna. Nullam eu nisi elementum, bibendum augue nec, rhoncus sem. Mauris aliquet mi mauris, sed lobortis urna viverra at.

Phasellus auctor, neque efficitur egestas ullamcorper, turpis justo lacinia eros, nec eleifend ligula risus at erat. Donec metus diam, faucibus vitae lobortis at, gravida in nulla. Morbi tincidunt quis mi at efficitur. Fusce tempor interdum placerat. Ut molestie magna fringilla efficitur ornare. Cras dapibus, dui id sagittis tincidunt, turpis sem tincidunt libero, eget pulvinar ante odio id eros. Aliquam porta turpis turpis, vitae faucibus arcu sollicitudin eu. Quisque finibus urna tortor, eget dictum quam porta sit amet. Curabitur ornare arcu ac massa pharetra, eget consequat ante eleifend. Nulla dignissim elit eget augue efficitur finibus. Vivamus ac nulla viverra, rutrum lorem in, pulvinar tellus. Nullam leo ipsum, semper vitae faucibus sit amet, consequat commodo est. Vivamus condimentum mauris vitae dignissim pellentesque. Fusce aliquet tortor mauris, eget aliquam lacus molestie a. Suspendisse pretium luctus leo, a ultrices neque dictum non.

Curabitur urna mauris, sodales vitae congue ut, vehicula vel neque. Maecenas a purus elementum, elementum dui eget, lobortis lorem. Phasellus mollis velit in dui faucibus ullamcorper. Sed sit amet est metus. Quisque lobortis lacinia enim, at tempus massa dictum in. Aliquam eget elit quis lacus faucibus consequat. Integer id tristique nulla, a ultricies diam. Curabitur vitae velit dictum, vehicula sapien et, dapibus metus. Maecenas viverra elit eu diam dignissim, vitae efficitur felis pharetra. Fusce iaculis lectus consectetur lacus dapibus lobortis. Mauris sodales facilisis eleifend. Phasellus volutpat rhoncus est ac efficitur. Vivamus vulputate pretium pretium.

Suspendisse sed leo in est accumsan scelerisque quis convallis metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque posuere ex in velit vehicula rhoncus. Mauris vitae turpis eu velit porta vulputate. Nunc interdum ornare tellus, et scelerisque est ultricies sed. Mauris feugiat nisi quis urna rhoncus faucibus. Mauris in mattis lorem, egestas varius justo. Pellentesque nec varius arcu, at venenatis ipsum. In a fermentum nulla. Phasellus volutpat egestas massa. Cras elementum at erat in hendrerit.

Nulla viverra lobortis ex, in sollicitudin diam euismod nec. Donec eu ultrices neque, ut aliquet ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada dapibus mauris, at porta est luctus vitae. Donec nec est sit amet mauris cursus iaculis vel vel neque. Nunc vitae turpis ultrices, ultricies nulla vitae, auctor sem. Vestibulum malesuada risus vel tincidunt vestibulum.

Mauris iaculis odio blandit, pretium ipsum at, pulvinar nunc. Sed consequat sagittis auctor. Vivamus non lacus in diam accumsan vestibulum et quis magna. Sed rhoncus commodo eros, eget pellentesque ex imperdiet vitae. Phasellus convallis in mi a semper. Sed elit massa, rutrum egestas eros in, aliquet cursus tellus. Fusce sed eleifend lorem. Phasellus at ligula urna. Ut dapibus dapibus risus, in accumsan sapien. Curabitur aliquam congue eros nec porta. Ut pharetra justo quis neque pretium eleifend.

Maecenas placerat viverra nunc ac accumsan. Ut mollis consectetur nulla quis tincidunt. Aliquam sit amet dui risus. Sed suscipit porttitor porta. In fringilla rhoncus convallis. Nulla ipsum risus, malesuada ut semper vel, ultrices eu diam. Morbi tempor orci at massa pulvinar venenatis. Praesent pharetra magna nec tempor ullamcorper. Integer sodales elementum suscipit. Vivamus sit amet dolor id quam feugiat tempor. Maecenas vitae hendrerit elit. Donec ac libero non felis auctor mattis. Sed aliquam, orci nec laoreet mollis, ex nisi euismod lacus, vel mattis est tellus ac leo. Proin a tincidunt lacus. Curabitur ac consequat ipsum. Maecenas vehicula, dolor ut ornare tincidunt, libero orci facilisis justo, vitae vehicula ligula ligula vitae ligula.

Maecenas sit amet enim iaculis, molestie est in, suscipit turpis. Donec nec egestas augue. Donec pretium, mauris sit amet pulvinar blandit, elit velit sollicitudin erat, nec blandit tellus sem nec lorem. Sed consequat.`;
type Case1 = StringIncludes<typeof str, "dolor sit">; // Result: true
